Assignment-3/MVC/Models/ErrorViewModel.cs
namespace MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Assignment-3/MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

 

    
}

Assignment-3/MVC/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MVC.Controllers
{
    [Route("[controller]")]
      [Route("[controller]/[action]")]
    public class loginController : Controller
    {
       

        public IActionResult Login()
        {
            return View();
        }

public IActionResult Profile()
{
    
    return View();
}
      
        
    }
}

Assignment-3/MVC/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}
<html>

<head>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script>
    $(document).ready(function () {
    $("#signup").click(function(){
    $("#alert1").hide();
     var ifname = $("#ifname").val()
     var ilname = $("#ilname").val()
     var iemail=$("#iemail").val()
    var icno = $("#icno").val()
    var idob = $("#idob").val()
    var password2 = $("#ipass").val()
    var password1 = $("#icpass").val()
 var reg=/^([a-zA-z0-9]+)$/;
    var pswlen = password2.length;
     if(ifname=="" || icno=="" || iemail=="" || password2=="" ||password1=="")
     {
        $("#alert1").show();
         $("#alert1").html("Please Enter value for Mandotary fields");
     
     
      return false;
     }
      if(!reg.test(password2))
   {
  
    $("#alert1").show();
     $("#alert1").html("Please Enter Alpha numeric And Special Characters.");
     
      return false;
  } 
 if(pswlen <6 || pswlen>12)
    {
       $("#alert1").show();
         $("#alert1").html("Password Min Length  6 and Max Length 12");
     
       return false;
      }
  else
     {
       if (password2 == password1) {
      
          var get=new Object();

          get.fname=$("#ifname").val()
          get.lname=$("#ilname").val()
          get.dob= $("#idob").val()
          get.cno=$("#icno").val()
          get.email= $("#iemail").val()
          get.password= $("#icpass").val()
          
           $.ajax({
           
           type:'Post',
           contentType:'Application/json',
           data:JSON.stringify(get),
           url:'https://localhost:7044/api/RegApi/PostData',
           success:function(result,status,xhr)
           {

              window.location.replace("https://localhost:7114/login/Login");

           }


           })
         
      }
      else
       {
         $("#alert1").show();
           $("#alert1").html("Enter char Are diffrent for Password! Please Confirm Password.");
       
        return false;
      
        
      }

    }
 })

    });

    
  </script>


</head>

<body>
  <div class="container">
  <div class="alert alert-danger text-center fw-bold" style="display: none;" id='alert1'></div>
   
      <div class="form-row">
        <div class="form-group col-md-3">
          <label for="ifname">First Name</label> <span style="color: red;">*</span>
          <input type="text" class="form-control" id="ifname" placeholder="First Name">

        </div>
        <div class="form-group col-md-3">
          <label for="ilname">Last Name</label>
          <input type="text" class="form-control" id="ilname" placeholder="Last Name">
        </div>
        <div class="form-group col-md-3">
          <label for="icno">Contact No</label> <span style="color: red;">*</span>
          <input type="number" class="form-control" id="icno" placeholder="Contact Number">
        </div>
        <div class="form-group col-md-3">
          <label for="idob">Date Of Birth</label>
          <input type="Date" class="form-control" id="idob" placeholder="Date Of Birth">
        </div>

        <div class="form-group col-md-3">
          <label for="iemail">Email</label> <span style="color: red;">*</span>
          <input type="email" class="form-control" id="iemail" placeholder="Email">
        </div>
        <div class="form-group col-md-3">
          <label for="ipass">Password</label> <span style="color: red;">*</span>
          <input type="password" class="form-control" id="ipass" placeholder="Password">


        </div>
        <div class="form-group col-md-3">
          <label for="icpass">Password</label> <span style="color:red;">*</span>
          <input type="password" class="form-control" id="icpass" placeholder="Confim Password">


        </div>

        <button type="submit" class="btn btn-primary mt-3" id="signup">Sign up</button>
        <button type="submit" class="btn btn-danger mt-3">Cancel</button>
      </div>
      <div class="form-group col-md-3 mt-1">
        <a class="link-primary" asp-action="Login" asp-controller="login">Already Have Account?</a>
      </div>
   
  </div>




</body>

</html>

Assignment-3/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="login" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assignment-3/MVC/Views/login/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
<html>
  <head>
 <script src="~/lib/jquery/dist/jquery.min.js"></script>
 <script>
  $(document).ready(function ()
  {
      
     $("#signin").click(function (){


       
      var eml=$("#lemail").val()
      var pass=$("#lpass").val()
       var get=new Object();

       if(eml=="" || pass=="")
       {
         $("#alert1").show();
            $("#alert1").html("Please enter Email and password");
       }
    
       get.email=$("#lemail").val()
       get.password=$("#lpass").val()

       if(get.email!=null && get.password!=null)
       {
        sessionStorage.setItem("email", get.email);
       $.ajax(
              {
                type:'POST',
                contentType:'Application/json',
                data:JSON.stringify(get),
                url:'https://localhost:7044/api/RegApi/login',
                success:function(result,status,xhr)
                {
           window.location.replace("https://localhost:7114/login/profile");
                
                }

              }
            )
        }
         
   })
     })
 </script>
  </head>
  <body>
     <div class="container">
      <div class="alert alert-danger text-center fw-bold"  style="display: none;" id='alert1'></div>
   
    
  <div class="form-row">
   <div class="form-group col-md-3">
      <label for="lemail">Email</label> <span style="color: red;">*</span>
      <input type="email" class="form-control" id="lemail" placeholder="Email">
    </div>
    <div class="form-group col-md-3">
      <label for="lpass">Password</label> <span style="color: red;">*</span>
      <input type="password" class="form-control" id="lpass" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary mt-2" id="signin">Sign In</button>
 <button type="submit" class="btn btn-danger mt-2">Cancel</button>
   </div>
   <div class="form-group col-md-3 mt-1">
   <a class="link-primary " asp-action="Index" asp-controller="Home">Don't Have Account?</a>

   </div>
       
  </div>
   </body>
</html>
 

Assignment-3/MVC/Views/login/Profile.cshtml
@{
  ViewData["Title"] = "Profile";
}
<html>

<head>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
  <script>
    let email1 = sessionStorage.getItem("email");
    console.log(email1);
    $(document).ready(function () {

      $.ajax({

        type: 'Get',
        contentType: 'Application/json',
        url: 'https://localhost:7044/api/RegApi/' + email1,
        success: function (result, status, xhr) {
          $('#dfname').append(result.fname);
          $('#dlname').append(result.lname);
          $('#dadd').append(result.dateadded);
          $('#dup').append(result.lastupdate);
          $('#pfname').val(result.fname);
          $('#plname').val(result.lname);
          $('#pcno').val(result.cno);
          $('#pemail').val(result.email);
          $('#ppass').val(result.password);
          var new1 = moment(result.dob).format('DD-MM-YYYY');
          $('#pdob').val(new1);
          sessionStorage.setItem("id", result.recid);
          console.log(result.dob);

        }
 })

    })
    function edit() {
      var editid = sessionStorage.getItem("id");
      $(document).ready(function () {
       


        var get = new Object()
        var x = $('#pdob').val();
        var n = x.split('-');
        get.fname = $('#pfname').val()
        get.dateadded = $('#dadd').text()
        get.lname = $('#plname').val()
        get.cno = $('#pcno').val()
       
        get.dob = n[2] + '-' + n[1] + '-' + n[0];
        get.email = $('#pemail').val()
        get.password = $('#ppass').val()
        var cpass = $('#pcpass').val()
        get.recid = editid;
        console.log(get.dob);
        var psw=$('#ppass').val()


  if (get.fname != "" && get.lname != "" && get.cno != "" && get.dob != "" && get.email != "" && get.password != "" && cpass != "")
         {
         
          if (get.password == cpass) {

            $.ajax({
              type: 'Put',
              data: JSON.stringify(get),
              contentType: 'Application/json',
              url: 'https://localhost:7044/api/RegApi',
              success: function (result, xhr, status) {
                window.location.replace("https://localhost:7114/login/profile");


              }

            })
          }
          else {
            $("#alert1").show();
          $("#alert1").html("Password & Confirm Password should be same");
         
            return false;
          }

        }
        
        else {
          $("#alert1").show();
        $("#alert1").html("Please Enter value for Mandotary fields");
        
          return false;

        }


      })

    }
  </script>
</head>

<body>

  <div class="container">



    <div class="form-row">
      <h4>Hi <label id="dfname"></label>&nbsp;<label id="dlname"></label></h4><br>
      <h4>Added on:</h4>
      <h4 id='dadd'></h4><br>
      <h4 id='dup'>Last Updated:</h4><br>

      <div class="alert alert-danger text-center fw-bold" style="display: none;" id='alert1'></div>

      <div class="form-group col-md-3">
        <label for="pfname">First Name</label> <span style="color: red;">*</span>
        <input type="text" class="form-control" id="pfname" placeholder="First Name">

      </div>
      <div class="form-group col-md-3">
        <label for="plname">Last Name</label>
        <input type="text" class="form-control" id="plname" placeholder="Last Name">
      </div>
      <div class="form-group col-md-3">
        <label for="pcno">Contact No</label> <span style="color: red;">*</span>
        <input type="number" class="form-control" id="pcno" placeholder="Contact Number">
      </div>
      <div class="form-group col-md-3">
        <label for="pdob">Date Of Birth</label>
        <input type="text" class="form-control" id="pdob" placeholder="Date Of Birth">
      </div>

      <div class="form-group col-md-3">
        <label for="pemail">Email</label> <span style="color: red;">*</span>
        <input type="email" class="form-control" id="pemail" placeholder="Email">
      </div>
      <div class="form-group col-md-3">
        <label for="ppass">Password</label> <span style="color: red;">*</span>
        <input type="password" class="form-control" id="ppass" placeholder="Password">


      </div>
      <div class="form-group col-md-3">
        <label for="pcpass">Password</label> <span style="color: red;">*</span>
        <input type="password" class="form-control" id="pcpass" placeholder="Confim Password">


      </div>

      <button type="submit" class="btn btn-primary mt-3" onclick="edit()">Update</button>
      <button type="submit" class="btn btn-danger mt-3">Cancel</button>
      <a class="btn btn-dark mt-3" href="https://localhost:7114/login/Login">Logout</a>
    </div>


  </div>


</body>

</html>